steps:
  - name: hello
    image: docker.io/library/busybox:latest
    commands:
      - echo hello from containerd
    when:
      event:
        - push
        - pull_request
        - tag
        - deployment
        - cron
        - manual
